# Array

In [1]:
import numpy as np       #importing the Numpy library. 'as' means Alternate name.

In [4]:
a=np.array([1,2,3])      #creating a array.
b=np.array(52)
print(a)                 #printing a array.
print(b)

[1 2 3]
52


In [5]:
type(a)                 #getting the data type.

numpy.ndarray

In [12]:
c=np.array([[1,2,3],[4,5,6]])     #2d array. Matrix format.

In [13]:
c                      

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,6],[6,5,6]]])    #23 array. Matrix format.

In [15]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 6],
        [6, 5, 6]]])

In [17]:
print(a.ndim)                  #ndim is used to print the dimensions of array.
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
0
2
3


# Conversion functions in numpy

In [20]:
A=np.array([10,20,30,40,50])   #declared an array

In [22]:
print(A)                       #printed the array

[10 20 30 40 50]


In [25]:
res=np.asarray(A,dtype="float",order="C")    #applied asarray on the array.

In [26]:
print(res)                      #returned array as a float dtype.

[10. 20. 30. 40. 50.]


In [28]:
B=np.array([[1,2,3],[4,5,6]])

In [29]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
res1=np.asarray(B,dtype="int",order="F")    #applied asarray on the array.

In [33]:
print(res1)

[[1 2 3]
 [4 5 6]]


In [34]:
# to print all the elements in a single dimension we use nditer.
# as we are column major, we will get the following result.
for i in np.nditer(res1):
    print(i)

1
4
2
5
3
6


In [35]:
res2=np.asarray(B,dtype="int",order="C")    #applied asarray on the array.

In [36]:
# as we are row major, we will get the following result.
for i in np.nditer(res2):
    print(i)

1
2
3
4
5
6


In [37]:
print(res2)

[[1 2 3]
 [4 5 6]]


In [38]:
s=b"hello welcome to python"   #b=bytes

In [39]:
c=np.frombuffer(s,dtype="S1",count=-1,offset=0)  #frombuffer method.

In [40]:
c

array([b'h', b'e', b'l', b'l', b'o', b' ', b'w', b'e', b'l', b'c', b'o',
       b'm', b'e', b' ', b't', b'o', b' ', b'p', b'y', b't', b'h', b'o',
       b'n'], dtype='|S1')

In [41]:
c=np.frombuffer(s,dtype="S1",count=10,offset=0)

In [42]:
c

array([b'h', b'e', b'l', b'l', b'o', b' ', b'w', b'e', b'l', b'c'],
      dtype='|S1')

In [43]:
l=[10,20,30,40]

In [44]:
d=np.fromiter(l,dtype="float",count=-1)   #fromiter method.
print(d)

[10. 20. 30. 40.]


# arange,linspace,logspace.

In [45]:
np.arange(0,10,2,dtype="int")  #arange.

array([0, 2, 4, 6, 8])

In [46]:
arr=np.arange(0,10,2,dtype="int")

In [48]:
print(arr)

[0 2 4 6 8]


In [53]:
arr=np.arange(0,10,dtype="float")

In [54]:
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
arr1=np.linspace(0,10,5)     #linspace

In [52]:
print(arr1)

[ 0.   2.5  5.   7.5 10. ]


In [56]:
arr1=np.linspace(0,10,5,endpoint=False,retstep=True)    #retstep means it will return as tuple and with the difference.
print(arr1)

(array([0., 2., 4., 6., 8.]), 2.0)


In [57]:
arr2=np.logspace(0,10,num=4,endpoint=False,base=2)  #Logspace
print(arr2)

[  1.           5.65685425  32.         181.01933598]


# Shape,reshape,zeros,ones,full,eye

In [58]:
x=[[10,20,30],[40,50,60]]  #by using shape we get the dimension of an array
np.shape(x)

(2, 3)

In [59]:
np.reshape(x,(3,2))  #by using reshape, we can change the shape of an array

array([[10, 20],
       [30, 40],
       [50, 60]])

In [60]:
np.zeros((2,3)) # matrix of all the zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.ones((2,3)) #matrix of all the ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.full((2,3),50)  #by using full, we will get a matrix of same element, which will be mentioned

array([[50, 50, 50],
       [50, 50, 50]])

In [63]:
np.eye(3)  #diagonal elements will be one's and non diagonal elements wil be 0's.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Accessing and slicing

In [64]:
p=np.array([10,20,30,40,50]) 

In [65]:
print(p[0])  #accessing data by using index

10


In [66]:
q=np.array([[10,20,30],[40,50,60]])  #2d array.

In [67]:
q[0][1]             #accessing data from 2d array.

20

In [68]:
q[0,1]

20

In [69]:
q[1,2]

60

In [71]:
r=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])

In [72]:
r[0,1,1]  #accessing the data from 3d array

50

In [73]:
v=np.array([10,20,30,40,50,60])   #slicing

In [75]:
print(v)

[10 20 30 40 50 60]


In [76]:
v[::]                              #slicing in 1d array

array([10, 20, 30, 40, 50, 60])

In [77]:
v[:4]

array([10, 20, 30, 40])

In [78]:
v[2:]

array([30, 40, 50, 60])

In [79]:
v[1:3]

array([20, 30])

In [81]:
u=np.array([[10,20,30],[40,50,60]])

In [82]:
print(u)

[[10 20 30]
 [40 50 60]]


In [83]:
u[0,0:2]                            #slicing in 2d array

array([10, 20])

In [84]:
u[1,0:2]

array([40, 50])

In [86]:
w=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])

In [87]:
w

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]]])

In [88]:
w[0,1,0:2]   #sliocing in 3d array

array([40, 50])

# Axis

In [96]:
#Axis=0 means we have to apply operations on column.
#Axis=1 means we have to apply operations on row.

f=np.array([[10,2,33],[4,50,6]])


In [97]:
print(f)

[[10  2 33]
 [ 4 50  6]]


In [98]:
np.sort(f,axis=0)    #here axis=0, hence operation has been done on columns.

array([[ 4,  2,  6],
       [10, 50, 33]])

In [99]:
np.sort(f,axis=1)   #here axis=1, hence operation has been done on rows.

array([[ 2, 10, 33],
       [ 4,  6, 50]])

In [101]:

Data=np.array([[1, 2, 3],[4, 5, 6]])

In [102]:
np.sum(Data,axis=1)     #sum of the elements of the first and second row.

array([ 6, 15])

In [104]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

In [116]:
a*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [117]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [119]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [120]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])